// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBOA6qjzr7dwyiEvs5Eg9HX227MHyFoq8',
    appId: '1:966347289957:android:c986500f729fc630439d8c',
    messagingSenderId: '966347289957',
    projectId: 'base-app-project-ept',
    storageBucket: 'base-app-project-ept.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1gEM50VGBMt-00AB0PYBieeKLSz0qKQ',
    appId: '1:966347289957:ios:94db330b7a948809439d8c',
    messagingSenderId: '966347289957',
    projectId: 'base-app-project-ept',
    storageBucket: 'base-app-project-ept.firebasestorage.app',
    iosBundleId: 'com.ept.baseapp.baseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1gEM50VGBMt-00AB0PYBieeKLSz0qKQ',
    appId: '1:966347289957:ios:94db330b7a948809439d8c',
    messagingSenderId: '966347289957',
    projectId: 'base-app-project-ept',
    storageBucket: 'base-app-project-ept.firebasestorage.app',
    iosBundleId: 'com.ept.baseapp.baseApp',
  );
}
